
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzlilvsvdliicxmfnxnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6bGlsdnN2ZGxpaWN4bWZueG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTE0MDQsImV4cCI6MjA1OTU4NzQwNH0.ruiiRzb91y8w9uFMHHO9vAV0cNNGlhXGjXwYhGp_IzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
